---
server:
    install: '1'
    timezone: UTC
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: movie-list, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/public
    servername: movie-list.dev
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-curl, php5-imagick, php5-geoip, php5-mysql]
composer:
    install: '1'
laravel:
    env: 'development'
